### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by simsausaurabh** [Glancify/Glancify#53]
useful link: https://travis-ci.org/

**Comment by simsausaurabh** [comment]
I am adding travis CI integration for testing but I think before that in our 'Glancify' org we should spearate the sections - Chrome extension, Firefox add on, and docs - gh-pages. 
@neelanshsahai @sakshee-19 @psikarwal @DeepakSandy @himanshusn 
Everyone up for this ?

**Comment by sakshee-19** [comment]
smjh nhi aya

**Comment by simsausaurabh** [comment]
Added :tada:
